name: Build and deploy
on:
  push:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
      - name: Build
        run: PR_SERVER_URL=http://165.232.44.57/api npx vue-cli-service build --mode production
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          username: "root"
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/park-run-courses/"
          rm: "true"
